apiVersion: batch/v1
kind: Job

metadata:
  name: report-aggregator

spec:
  template:
    metadata:
      labels:
        app: report-aggregator

    spec:
      restartPolicy: Never

      containers:
        - name: aggregator
          image: lethalfore/qa-intelligence-mcp:1.2.3
          imagePullPolicy: Always

          workingDir: /app

          env:
            - name: AWS_DEFAULT_REGION
              value: "ap-south-1"

            - name: S3_BUCKET
              value: "qa-intelligence-reports-sathishp"

          command:
            - sh
            - -c
            - |
              echo "Downloading worker reports..."
              python aggregator/download_reports.py

              echo "Merging reports..."
              python aggregator/merge_reports.py

              echo "Aggregation completed."