apiVersion: batch/v1
kind: Job

metadata:
  name: playwright-regression

spec:
  completions: 3
  parallelism: 3

  template:
    metadata:
      labels:
        app: playwright-worker

    spec:
      restartPolicy: Never

      containers:
        - name: playwright
          image: lethalfore/qa-playwright-worker:1.2.0
          imagePullPolicy: Always

          env:
            - name: CI
              value: "true"

            - name: AWS_DEFAULT_REGION
              value: "ap-south-1"

            - name: S3_BUCKET
              value: "qa-intelligence-reports-sathishp"

          command:
            - sh
            - -c
            - |
              export WORKER_NAME=worker-$(hostname | tail -c 2)

              echo "======================================"
              echo "Running as ${WORKER_NAME}"
              echo "======================================"

              npx playwright test tests/smoke.spec.ts

              echo "Uploading report to S3..."

              aws s3 cp \
                reports/${WORKER_NAME}/results.json \
                s3://${S3_BUCKET}/${WORKER_NAME}.json

              echo "Upload completed."